package:
  name: alsa-lib-cos7-armv7l
  version: 1.1.8

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/alsa-lib-1.1.8-1.el7.armv7hl.rpm
    sha256: f7899ada381710f010966a41b5a485b0a114dccf19b1729e58d6991adb08ae6a
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/alsa-lib-1.1.8-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.alsa-project.org/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/alsa-lib-1.1.8/COPYING
  summary: "(CDT) The Advanced Linux Sound Architecture (ALSA) library"
  description: |
        The Advanced Linux Sound Architecture (ALSA) provides audio and MIDI
        functionality to the Linux operating system.  This package includes the ALSA
        runtime libraries to simplify application programming and provide higher level
        functionality as well as support for the older OSS API, providing binary
        compatibility for most OSS programs.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
