package:
  name: java-1.7.0-openjdk-cos7-armv7l
  version: 1.7.0.261

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.armv7hl.rpm
    sha256: 88d6192f5d666357fb94ae9b85e761826580b653227a650c954701e0dfb944c1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - java-1.7.0-openjdk-headless-cos7-armv7l ==1.7.0.261 *_{{ cdt_build_number|int + 1000 }}
  host:
    - java-1.7.0-openjdk-headless-cos7-armv7l ==1.7.0.261 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - java-1.7.0-openjdk-headless-cos7-armv7l ==1.7.0.261 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: (CDT) OpenJDK Runtime Environment
  description: |
    The OpenJDK runtime environment.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
