package:
  name: libnl3-cos7-armv7l
  version: 3.2.28

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libnl3-3.2.28-4.el7.armv7hl.rpm
    sha256: ae62cac147fd4fb23b1be1922aad823842e11b6d75cb69920ada57b84a76bdae
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libnl3-3.2.28-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: libnl3-license
  summary: (CDT) Convenience library for kernel netlink sockets
  description: |
    This package contains a convenience library to simplify using the Linux
    kernel's netlink sockets interface for network manipulation

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
