package:
  name: libx11-devel-cos7-armv7l
  version: 1.6.7

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libX11-devel-1.6.7-2.el7.armv7hl.rpm
    sha256: 1759bdcaca531c3bae3ee74a46d303a35caac229e7c87a8988d37874f195d383
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libX11-1.6.7-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-armv7l ==1.6.7 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-cos7-armv7l ==1.6.7 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libx11-cos7-armv7l ==1.6.7 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: x11-license
  summary: (CDT) Development files for libX11
  description: |
    X.Org X11 libX11 development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
