package:
  name: libxrandr-devel-cos7-armv7l
  version: 1.5.1

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXrandr-devel-1.5.1-2.el7.armv7hl.rpm
    sha256: 3e4236ac0e82b8465036fd6a23eda96506adae9c63d40ab3d58d866de7b5d7c1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXrandr-1.5.1-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxrandr-cos7-armv7l ==1.5.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxrandr-cos7-armv7l ==1.5.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxrandr-cos7-armv7l ==1.5.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) X.Org X11 libXrandr development package"
  description: |
        X.Org X11 libXrandr development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
