package:
  name: gtkmm24-devel-cos7-armv7l
  version: 2.24.5

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/gtkmm24-devel-2.24.5-1.el7.armv7hl.rpm
    sha256: 0b0611a7ada70ce4053e6f879b8fef2cd6daa8372aa92ddf477b569b34f04ffa
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/gtkmm24-2.24.5-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.gtkmm.org/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Headers for developing programs that will use gtkmm24."
  description: |
        This package contains the static libraries and header files needed for
        developing gtkmm applications.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
