package:
  name: libsm-cos7-armv7l
  version: 1.2.2

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libSM-1.2.2-2.el7.armv7hl.rpm
    sha256: c1bde053c04f1c1c00de95cc094765b314494b9e0b114bbc5368c40e1a077031
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libSM-1.2.2-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libSM-1.2.2/COPYING
  summary: "(CDT) X.Org X11 SM runtime library"
  description: |
        The X.Org X11 SM (Session Management) runtime library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
