package:
  name: cups-devel-cos7-armv7l
  version: 1.6.3

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/cups-devel-1.6.3-51.el7.armv7hl.rpm
    sha256: 33826e916764b0fe347f5eeddcf8471b9308078342c4c3b5c0dc9615eaa448b9
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/cups-1.6.3-51.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cups-libs-cos7-armv7l ==1.6.3 *_{{ cdt_build_number|int + 1000 }}
  host:
    - cups-libs-cos7-armv7l ==1.6.3 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - cups-libs-cos7-armv7l ==1.6.3 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.cups.org/
  license: LGPLv2
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) CUPS printing system - development environment"
  description: |
        CUPS printing system provides a portable printing layer for UNIX® operating
        systems. This is the development package for creating additional printer
        drivers, and other CUPS services.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
