package:
  name: libxft-devel-cos7-armv7l
  version: 2.3.2

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libXft-devel-2.3.2-2.el7.armv7hl.rpm
    sha256: 6a11a66675ab7260795e548bc0ad6c0536160c92cd3234feb3cc25989e8db6b9
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXft-2.3.2-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxft-cos7-armv7l ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxft-cos7-armv7l ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxft-cos7-armv7l ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libXft-license
  summary: (CDT) X.Org X11 libXft development package
  description: |
    X.Org X11 libXft development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
