package:
  name: alsa-lib-devel-cos7-armv7l
  version: 1.1.8

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/alsa-lib-devel-1.1.8-1.el7.armv7hl.rpm
    sha256: 3f411507234b5bf5f7c5a8dbd33a8e2ee53cabed9695a4293245897e98d855e8
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/alsa-lib-1.1.8-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - alsa-lib-cos7-armv7l ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
  host:
    - alsa-lib-cos7-armv7l ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - alsa-lib-cos7-armv7l ==1.1.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.alsa-project.org/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: alsa-lib-license
  summary: (CDT) Development files from the ALSA library
  description: |
    The Advanced Linux Sound Architecture (ALSA) provides audio and MIDI
    functionality to the Linux operating system.  This package includes the ALSA
    development libraries for developing against the ALSA libraries and
    interfaces.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
