package:
  name: pkgconfig-cos7-armv7l
  version: 0.27.1

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/pkgconfig-0.27.1-4.el7.armv7hl.rpm
    sha256: 57a470d56e41c4de10d0a05ee124a773fe58c35573a846734c448d2f85d35199
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pkgconfig-0.27.1-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://pkgconfig.freedesktop.org
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/pkgconfig-0.27.1/COPYING
  summary: "(CDT) A tool for determining compilation options"
  description: |
        The pkgconfig tool determines compilation options. For each required library,
        it reads the configuration file and outputs the necessary compiler and linker
        flags.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
