package:
  name: libjpeg-turbo-cos7-armv7l
  version: 1.2.90

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libjpeg-turbo-1.2.90-8.el7.armv7hl.rpm
    sha256: 3c813bf9a5bb958a5a46bc635176737c8fefb20d9186832522342cb21c2bb823
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libjpeg-turbo-1.2.90-8.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://sourceforge.net/projects/libjpeg-turbo
  license: IJG
  license_family: Other
  license_file: libjpeg-turbo-license
  summary: (CDT) A MMX/SSE2 accelerated library for manipulating JPEG image files
  description: |
    The libjpeg-turbo package contains a library of functions for manipulating
    JPEG images.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
