package:
  name: libnl3-cli-cos7-armv7l
  version: 3.2.28

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libnl3-cli-3.2.28-4.el7.armv7hl.rpm
    sha256: 3aa4e20f0250f5b80021a7710ebad2fe40dd269375b6e54c0663ec2af029cee5
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libnl3-3.2.28-4.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libnl3-cos7-armv7l ==3.2.28 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libnl3-cos7-armv7l ==3.2.28 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libnl3-cos7-armv7l ==3.2.28 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libnl3-cli-3.2.28/COPYING
  summary: "(CDT) Command line interface utils for libnl3"
  description: |
        This package contains various libnl3 utils and additional libraries on which
        they depend

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
