package:
  name: xorg-x11-proto-devel-cos7-armv7l
  version: 2018.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/xorg-x11-proto-devel-2018.4-1.el7.noarch.rpm
    sha256: ed33c07dd19aae73edaef6cb5daeca44fae87aa7fba16d5de6aad4c244f5232f
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/xorg-x11-proto-devel-2018.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/xorg-x11-proto-devel-2018.4/COPYING-xineramaproto
  summary: "(CDT) X.Org X11 Protocol headers"
  description: |
        X.Org X11 Protocol headers

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
