package:
  name: libxext-cos7-armv7l
  version: 1.3.3

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libXext-1.3.3-3.el7.armv7hl.rpm
    sha256: 0eab0c84f4c1bb758e42816d645c1796ad1c4a13b19a56abd91854177afdc679
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXext-1.3.3-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libXext-1.3.3/COPYING
  summary: "(CDT) X.Org X11 libXext runtime library"
  description: |
        X.Org X11 libXext runtime library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
