package:
  name: libnl-cos7-armv7l
  version: 1.1.4

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libnl-1.1.4-3.el7.armv7hl.rpm
    sha256: e49b9c2cc71d3257fa8e7cba94655770d842ac2b1594153fca7c9079c3f18a8b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libnl-1.1.4-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  license_file: libnl-devel-license
  summary: (CDT) Convenience library for kernel netlink sockets
  description: |
    This package contains a convenience library to simplify using the Linux
    kernel's netlink sockets interface for network manipulation

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
