package:
  name: libxxf86vm-devel-cos7-armv7l
  version: 1.1.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXxf86vm-devel-1.1.4-1.el7.armv7hl.rpm
    sha256: ff80cfc466861a5e4ee45f9b95599d9287d146374c8bd8da64e8df7cd5db7dfe
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXxf86vm-1.1.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxxf86vm-cos7-armv7l ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxxf86vm-cos7-armv7l ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxxf86vm-cos7-armv7l ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libxxf86vm-license
  summary: "(CDT) X.Org X11 libXxf86vm development package"
  description: |
        X.Org X11 libXxf86vm development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
