package:
  name: libthai-cos7-armv7l
  version: 0.1.14

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libthai-0.1.14-9.el7.armv7hl.rpm
    sha256: 51a3977082b59c46763adb875a87efd13462d8ae6cf47350f0f36bf05519b575
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libthai-0.1.14-9.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://linux.thai.net
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libthai-0.1.14/COPYING
  summary: "(CDT) Thai language support routines"
  description: |
        LibThai is a set of Thai language support routines aimed to ease developers'
        tasks to incorporate Thai language support in their applications. It includes
        important Thai-specific functions e.g. word breaking, input and output methods
        as well as basic character and string supports.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
