package:
  name: java-1.7.0-openjdk-headless-cos7-armv7l
  version: 1.7.0.261

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/java-1.7.0-openjdk-headless-1.7.0.261-2.6.22.2.el7_8.armv7hl.rpm
    sha256: 70cfaef11922a2b7943a5346816fafde07cd20bb78d604bfafe1ece28946b399
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-armv7l >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - jpackage-utils-cos7-armv7l >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-armv7l >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - jpackage-utils-cos7-armv7l >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - chkconfig-cos7-armv7l >=1.7 *_{{ cdt_build_number|int + 1000 }}
    - copy-jdk-configs-cos7-armv7l >=3.3 *_{{ cdt_build_number|int + 1000 }}
    - jpackage-utils-cos7-armv7l >=3.4.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.arm/LICENSE
  summary: "(CDT) The OpenJDK runtime environment without audio and video support"
  description: |
        The OpenJDK runtime environment without audio and video

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
