package:
  name: xcb-util-renderutil-devel-cos7-armv7l
  version: 0.3.9

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/xcb-util-renderutil-devel-0.3.9-3.el7.armv7hl.rpm
    sha256: 6db748f6aed62c43416031c8b4c6eb54f0792caad31c73da2998c5ceb0820572
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/xcb-util-renderutil-0.3.9-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - xcb-util-renderutil-cos7-armv7l ==0.3.9 *_{{ cdt_build_number|int + 1000 }}
  host:
    - xcb-util-renderutil-cos7-armv7l ==0.3.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - xcb-util-renderutil-cos7-armv7l ==0.3.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: xcb-util-renderutil-license
  summary: (CDT) Development and header files for xcb-util-renderutil
  description: |
    Development files for xcb-util-renderutil.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
