package:
  name: mesa-dri-drivers-cos7-armv7l
  version: 18.3.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-dri-drivers-18.3.4-10.el7.armv7hl.rpm
    sha256: cef625c16f0f39f4ff191ff3d2e26cbebee7a5a4f16821d17e2df233bbb70915
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libdrm-cos7-armv7l >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libdrm-cos7-armv7l >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libdrm-cos7-armv7l >=2.4.83 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Mesa-based DRI drivers"
  description: |
        Mesa-based DRI drivers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
