package:
  name: gtk2-cos7-armv7l
  version: 2.24.31

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/gtk2-2.24.31-1.el7.armv7hl.rpm
    sha256: 9d61edf9a1431951fc19757d7cae6345c4c31266aaf533c9989c0d2ed55864ea
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/gtk2-2.24.31-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - atk-cos7-armv7l >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - glib2-cos7-armv7l >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - libxrandr-cos7-armv7l >=1.2.99.4 *_{{ cdt_build_number|int + 1000 }}
    - libtiff-cos7-armv7l >=3.6.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - atk-cos7-armv7l >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - glib2-cos7-armv7l >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - libxrandr-cos7-armv7l >=1.2.99.4 *_{{ cdt_build_number|int + 1000 }}
    - libtiff-cos7-armv7l >=3.6.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - atk-cos7-armv7l >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - glib2-cos7-armv7l >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - libxrandr-cos7-armv7l >=1.2.99.4 *_{{ cdt_build_number|int + 1000 }}
    - libtiff-cos7-armv7l >=3.6.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.gtk.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/gtk2-2.24.31/COPYING
  summary: "(CDT) The GIMP ToolKit (GTK+), a library for creating GUIs for X"
  description: |
        GTK+ is a multi-platform toolkit for creating graphical user interfaces.
        Offering a complete set of widgets, GTK+ is suitable for projects ranging from
        small one-off tools to complete application suites.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
