package:
  name: mesa-libglu-devel-cos7-x86_64
  version: 9.0.0

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-devel-9.0.0-4.el7.x86_64.rpm
    sha256: 16a6d263808c9fdce8fd2a8485bcf6573ff6c32921528dd2eb0d57d4351bae29
    no_hoist: true
    folder: binary

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-khr-devel-cos7-x86_64 ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - mesa-libglu-cos7-x86_64 ==9.0.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - mesa-khr-devel-cos7-x86_64 ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - mesa-libglu-cos7-x86_64 ==9.0.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - mesa-khr-devel-cos7-x86_64 ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - mesa-libglu-cos7-x86_64 ==9.0.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa libGLU development package
  description: |
    Mesa libGLU development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
