package:
  name: mesa-libgl-devel-cos7-armv7l
  version: 18.3.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/mesa-libGL-devel-18.3.4-10.el7.armv7hl.rpm
    sha256: 7e9dffe6de0179f8d639f7a4255bcc53f6bfe2e17265fb478562d51c917f995e
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-18.3.4-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-libgl-cos7-armv7l ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - mesa-libgl-cos7-armv7l ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - mesa-libgl-cos7-armv7l ==18.3.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Mesa libGL development package"
  description: |
        Mesa libGL development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
