package:
  name: pciutils-cos7-armv7l
  version: 3.5.1

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/pciutils-3.5.1-3.el7.armv7hl.rpm
    sha256: 9d976adb9e40a784be1d295cdeff54c501b16a853dbc90243c34a6d1ce7ffcc4
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pciutils-3.5.1-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - pciutils-libs-cos7-armv7l ==3.5.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - pciutils-libs-cos7-armv7l ==3.5.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - pciutils-libs-cos7-armv7l ==3.5.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: pciutils-license
  summary: (CDT) PCI bus related utilities
  description: |
    The pciutils package contains various utilities for inspecting and setting
    devices connected to the PCI bus. The utilities provided require kernel
    version 2.1.82 or newer (which support the /proc/bus/pci interface).

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
