package:
  name: libxi-cos7-armv7l
  version: 1.7.9

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXi-1.7.9-1.el7.armv7hl.rpm
    sha256: 0c2df9c11b8cf933256b7b84e2f7f41f1b7c4c931734e45750bbae3d50ad5878
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXi-1.7.9-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libXi-1.7.9/COPYING
  summary: "(CDT) X.Org X11 libXi runtime library"
  description: |
        X.Org X11 libXi runtime library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
