package:
  name: freetype-devel-cos7-armv7l
  version: 2.8

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/freetype-devel-2.8-14.el7.armv7hl.rpm
    sha256: 2d6238d98b143fe99cdb63ce313841358bf6763f0c4f8637b42d4423981ee39b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/freetype-2.8-14.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - freetype-cos7-armv7l ==2.8 *_{{ cdt_build_number|int + 1000 }}
  host:
    - freetype-cos7-armv7l ==2.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - freetype-cos7-armv7l ==2.8 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freetype.org
  license: (FTL or GPLv2+) and BSD and MIT and Public Domain and zlib with acknowledgement
  license_family: GPL2
  license_file: freetype-license.txt
  summary: (CDT) FreeType development libraries and header files
  description: |
    The freetype-devel package includes the static libraries and header files for
    the FreeType font rendering engine.  Install freetype-devel if you want to
    develop programs which will use FreeType.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
