package:
  name: at-spi-devel-cos7-armv7l
  version: 1.32.0

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/at-spi-devel-1.32.0-12.el7.armv7hl.rpm
    sha256: 6d31801f5c39c14c4c38540041b5aa3fa4a4990d5d440d11afb3ceb1e677628e
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/at-spi-1.32.0-12.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - orbit2-devel-cos7-armv7l >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-cos7-armv7l ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-cos7-armv7l >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-cos7-armv7l >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-cos7-armv7l >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - orbit2-devel-cos7-armv7l >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-cos7-armv7l ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-cos7-armv7l >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-cos7-armv7l >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-cos7-armv7l >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - orbit2-devel-cos7-armv7l >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-cos7-armv7l ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-cos7-armv7l >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-cos7-armv7l >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-cos7-armv7l >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
test:
  commands:
    - echo "it installs!"

about:
  home: http://developer.gnome.org/projects/gap/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: at-spi-license
  summary: (CDT) Development files for at-spi
  description: |
    This package contains libraries, header files and developer documentation
    needed for developing applications that interact directly with at-spi.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
