package:
  name: rdma-core-cos7-armv7l
  version: 22.4

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/rdma-core-22.4-5.el7.armv7hl.rpm
    sha256: 6f9fb33244f95e6cd9c96418eb7c99b2e32c3cfc61c89e6787552b66beaf5ae2
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/rdma-core-22.4-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/rdma-core-22.4/COPYING.md
  summary: "(CDT) RDMA core userspace libraries and daemons"
  description: |
        RDMA core userspace infrastructure and documentation, including initscripts,
        kernel driver-specific modprobe override configs, IPoIB network scripts,
        dracut rules, and the rdma-ndd utility.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
