package:
  name: pango-devel-cos7-armv7l
  version: 1.42.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/pango-devel-1.42.4-4.el7_7.armv7hl.rpm
    sha256: 04a30528a349a3d0192edb437b678a1503835f06473b93d27b9fdd437afdf61c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pango-1.42.4-4.el7_7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.pango.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Development files for pango"
  description: |
        The pango-devel package includes the header files and developer documentation
        for the pango package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
