package:
  name: pango-devel-cos7-armv7l
  version: 1.42.4

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/pango-devel-1.42.4-4.el7_7.armv7hl.rpm
    sha256: 04a30528a349a3d0192edb437b678a1503835f06473b93d27b9fdd437afdf61c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pango-1.42.4-4.el7_7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - cairo-devel-cos7-armv7l >=1.12.10 *_{{ cdt_build_number|int + 1000 }}
    - fontconfig-devel-cos7-armv7l >=2.11.91 *_{{ cdt_build_number|int + 1000 }}
    - freetype-devel-cos7-armv7l >=2.1.5 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-cos7-armv7l >=2.56.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l ==1.42.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - cairo-devel-cos7-armv7l >=1.12.10 *_{{ cdt_build_number|int + 1000 }}
    - fontconfig-devel-cos7-armv7l >=2.11.91 *_{{ cdt_build_number|int + 1000 }}
    - freetype-devel-cos7-armv7l >=2.1.5 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-cos7-armv7l >=2.56.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l ==1.42.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - cairo-devel-cos7-armv7l >=1.12.10 *_{{ cdt_build_number|int + 1000 }}
    - fontconfig-devel-cos7-armv7l >=2.11.91 *_{{ cdt_build_number|int + 1000 }}
    - freetype-devel-cos7-armv7l >=2.1.5 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-cos7-armv7l >=2.56.1 *_{{ cdt_build_number|int + 1000 }}
    - pango-cos7-armv7l ==1.42.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.pango.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: pango-copying
  summary: (CDT) Development files for pango
  description: |
    The pango-devel package includes the header files and developer documentation
    for the pango package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
