package:
  name: pango-cos7-armv7l
  version: 1.42.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/pango-1.42.4-4.el7_7.armv7hl.rpm
    sha256: a71be09e0906bedf9376f8d16b8a4878ef6b34792d1fc3aa3d957da9a37dd6d9
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pango-1.42.4-4.el7_7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.pango.org
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/pango-1.42.4/COPYING
  summary: "(CDT) System for layout and rendering of internationalized text"
  description: |
        Pango is a library for laying out and rendering of text, with an emphasis on
        internationalization. Pango can be used anywhere that text layout is needed,
        though most of the work on Pango so far has been done in the context of the
        GTK+ widget toolkit. Pango forms the core of text and font handling for GTK+.
        Pango is designed to be modular; the core Pango layout engine can be used with
        different font backends.  The integration of Pango with Cairo provides a
        complete solution with high quality text handling and graphics rendering.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
