package:
  name: libibmad-cos7-armv7l
  version: 1.3.13

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libibmad-1.3.13-1.el7.armv7hl.rpm
    sha256: 5a9b02ad5aec4fb6d1c9d04ff8b2855f4f25c0f714165e7efa03f0b3e4b0320c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libibmad-1.3.13-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libibmad-1.3.13/COPYING
  summary: "(CDT) OpenFabrics Alliance InfiniBand MAD library"
  description: |
        libibmad provides low layer IB functions for use by the IB diagnostic and
        management programs. These include MAD, SA, SMP, and other basic IB functions.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
