package:
  name: xcb-util-devel-cos7-armv7l
  version: 0.4.0

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/xcb-util-devel-0.4.0-2.el7.armv7hl.rpm
    sha256: 0a996dec47c3d90a003a7716fd5fb040d4abf91f61b004cfa2118349b7643dad
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/xcb-util-0.4.0-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - xcb-util-cos7-armv7l ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - xcb-util-cos7-armv7l ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - xcb-util-cos7-armv7l ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Development and header files for xcb-util"
  description: |
        Development files for xcb-util.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
