package:
  name: libsoup-devel-cos7-armv7l
  version: 2.62.2

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libsoup-devel-2.62.2-2.el7.armv7hl.rpm
    sha256: 94a8c2b807a597fcf6fa8023fee15441c304ada4ac97a663852f011a58fc247b
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libsoup-2.62.2-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libsoup-cos7-armv7l ==2.62.2 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libsoup-cos7-armv7l ==2.62.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libsoup-cos7-armv7l ==2.62.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://wiki.gnome.org/Projects/libsoup
  license: LGPLv2
  license_family: LGPL
  license_file: libsoup-license
  summary: (CDT) Header files for the Soup library
  description: |
    Libsoup is an HTTP library implementation in C. This package allows you to
    develop applications that use the libsoup library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
