package:
  name: cups-libs-cos7-armv7l
  version: 1.6.3

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/cups-libs-1.6.3-51.el7.armv7hl.rpm
    sha256: 12c7a1def1e30b0ecd6591566f9f4c2a05205471c34dae685eee09508e7b2b65
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/cups-1.6.3-51.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.cups.org/
  license: LGPLv2 and zlib
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/cups-libs-1.6.3/LICENSE.txt
  summary: "(CDT) CUPS printing system - libraries"
  description: |
        CUPS printing system provides a portable printing layer for UNIX® operating
        systems. It has been developed by Apple Inc. to promote a standard printing
        solution for all UNIX vendors and users. CUPS provides the System V and
        Berkeley command-line interfaces. The cups-libs package provides libraries
        used by applications to use CUPS natively, without needing the lp/lpr
        commands.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
