package:
  name: libbonobo-devel-cos7-armv7l
  version: 2.32.1

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libbonobo-devel-2.32.1-7.el7.armv7hl.rpm
    sha256: b4fe59bba5b281b1d8b3c720da33277e9ba2a26d5ffccd64308478106eabd081
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libbonobo-2.32.1-7.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - orbit2-devel-cos7-armv7l >=2.7.5 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-cos7-armv7l ==2.32.1 *_{{ cdt_build_number|int + 1000 }}
    - libxml2-devel-cos7-armv7l >=2.4.21 *_{{ cdt_build_number|int + 1000 }}
  host:
    - orbit2-devel-cos7-armv7l >=2.7.5 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-cos7-armv7l ==2.32.1 *_{{ cdt_build_number|int + 1000 }}
    - libxml2-devel-cos7-armv7l >=2.4.21 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - orbit2-devel-cos7-armv7l >=2.7.5 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-cos7-armv7l ==2.32.1 *_{{ cdt_build_number|int + 1000 }}
    - libxml2-devel-cos7-armv7l >=2.4.21 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://ftp.gnome.org
  license: GPLv2+ and LGPLv2+
  license_family: GPL2
  license_file:
    - libbonobo-copying
    - libbonobo-copying.lib
  summary: (CDT) Libraries and headers for libbonobo
  description: |
    Bonobo is a component system based on CORBA, used by the GNOME desktop.  This
    package contains header files used to compile programs that use Bonobo.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
