package:
  name: systemd-devel-cos7-armv7l
  version: 219

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/systemd-devel-219-78.el7.armv7hl.rpm
    sha256: 4175fe3565ffe85a360acf4bda779cd6f66895f853380de1918dd0db4bc120b9
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/systemd-219-78.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - systemd-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
  host:
    - systemd-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - systemd-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
    - systemd-libs-cos7-armv7l ==219 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.freedesktop.org/wiki/Software/systemd
  license: LGPLv2+ and MIT
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Development headers for systemd"
  description: |
        Development headers and auxiliary files for developing applications for
        systemd.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
