package:
  name: libxtst-cos7-armv7l
  version: 1.2.3

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXtst-1.2.3-1.el7.armv7hl.rpm
    sha256: 9878447bc86bb1cbf9d217e88a0caab182cd76bea7b3ab38669bbb2a9071fbab
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXtst-1.2.3-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libXtst-1.2.3/COPYING
  summary: "(CDT) X.Org X11 libXtst runtime library"
  description: |
        X.Org X11 libXtst runtime library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
