package:
  name: libibmad-devel-cos7-armv7l
  version: 1.3.13

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libibmad-devel-1.3.13-1.el7.armv7hl.rpm
    sha256: 614c2b9bc48a5a5eaea10626b85ff98332200fc4a76efef60a250b1339540c69
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libibmad-1.3.13-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libibmad-cos7-armv7l ==1.3.13 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libibmad-cos7-armv7l ==1.3.13 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libibmad-cos7-armv7l ==1.3.13 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Development files for the libibmad library"
  description: |
        Development files for the libibmad library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
