package:
  name: pixman-cos7-armv7l
  version: 0.34.0

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/pixman-0.34.0-1.el7.armv7hl.rpm
    sha256: 9147c330eb7aabd2c0f585b884b1059dc8082029d79f94e34e7f395c20c8b573
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/pixman-0.34.0-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://cgit.freedesktop.org/pixman/
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Pixel manipulation library"
  description: |
        Pixman is a pixel manipulation library for X and cairo.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
