package:
  name: libxkbcommon-devel-cos7-armv7l
  version: 0.7.1

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libxkbcommon-devel-0.7.1-3.el7.armv7hl.rpm
    sha256: 1c64ea468deb323560dc868e582f844bee400a58d58794f7d4356d3b99d2fe05
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libxkbcommon-0.7.1-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxkbcommon-cos7-armv7l ==0.7.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxkbcommon-cos7-armv7l ==0.7.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxkbcommon-cos7-armv7l ==0.7.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libxkbcommon-license
  summary: (CDT) X.Org X11 XKB parsing development package
  description: |
    X.Org X11 XKB parsing development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
