package:
  name: libxrender-devel-cos7-armv7l
  version: 0.9.10

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libXrender-devel-0.9.10-1.el7.armv7hl.rpm
    sha256: c645c635aee9255690ce00d2516094279f497f518d7767dda8069871a4493ffc
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXrender-0.9.10-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxrender-cos7-armv7l ==0.9.10 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxrender-cos7-armv7l ==0.9.10 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxrender-cos7-armv7l ==0.9.10 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) X.Org X11 libXrender development package"
  description: |
        X.Org X11 libXrender development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
