package:
  name: libxml2-devel-cos7-armv7l
  version: 2.9.1

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libxml2-devel-2.9.1-6.el7.5.armv7hl.rpm
    sha256: 011b5c35a42db3be906511edd31273c5a25607f1f00c86ccc502370ba604b4f1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libxml2-2.9.1-6.el7.5.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxml2-cos7-armv7l ==2.9.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxml2-cos7-armv7l ==2.9.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxml2-cos7-armv7l ==2.9.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libxml2-devel-2.9.1/Copyright
  summary: "(CDT) Libraries, includes, etc. to develop XML and HTML applications"
  description: |
        Libraries, include files, etc you can use to develop XML applications. This
        library allows to manipulate XML files. It includes support to read, modify
        and write XML and HTML files. There is DTDs support this includes parsing and
        validation even with complex DtDs, either at parse time or later once the
        document has been modified. The output can be a simple SAX stream or and in-
        memory DOM like representations. In this case one can use the built-in XPath
        and XPointer implementation to select sub nodes or ranges. A flexible
        Input/Output mechanism is available, with existing HTTP and FTP modules and
        combined to an URI library.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
