package:
  name: mesa-libglu-devel-cos6-x86_64
  version: 11.0.7

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/mesa-libGLU-devel-11.0.7-4.el6.x86_64.rpm
    sha256: b9ddb0d38fed0050b9145b6bb69b2fc6ee014df9bf3004316d222cf5bd8f167b
    no_hoist: true
    folder: binary

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - mesa-libglu-cos6-x86_64 ==11.0.7 *_{{ cdt_build_number|int + 1000 }}
  host:
    - mesa-libglu-cos6-x86_64 ==11.0.7 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*
  run:
    - mesa-libglu-cos6-x86_64 ==11.0.7 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Mesa libGL development package
  description: |
    Mesa libGL development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
