package:
  name: xcb-util-wm-devel-cos7-armv7l
  version: 0.4.1

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/xcb-util-wm-devel-0.4.1-5.el7.armv7hl.rpm
    sha256: 05c5fd581c18b9026b4eaf63a012c739ff580794d29c0dd5e4861849bcd7b5cd
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/xcb-util-wm-0.4.1-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://xcb.freedesktop.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) Development and header files for xcb-util-vm"
  description: |
        Development files for xcb-util-wm.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
