package:
  name: rdma-core-devel-cos7-armv7l
  version: 22.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/rdma-core-devel-22.4-5.el7.armv7hl.rpm
    sha256: 9bebccb90b2a5f6dae45a5a572377a2fac4e9bd321cbf4a94053f0ccc1bc46c7
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/rdma-core-22.4-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - ibacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibumad-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibverbs-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - librdmacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - ibacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibumad-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibverbs-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - librdmacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - ibacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibumad-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - libibverbs-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - librdmacm-cos7-armv7l ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) RDMA core development libraries and headers"
  description: |
        RDMA core development libraries and headers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
