package:
  name: libxxf86vm-cos7-armv7l
  version: 1.1.4

source:
  - url: http://mirror.centos.org/altarch/7/os/armhfp/Packages/libXxf86vm-1.1.4-1.el7.armv7hl.rpm
    sha256: 0fddc27aa2b798b2f50232f5b82c65429cd4fac3230d329af5a29ebdbac75d38
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXxf86vm-1.1.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libx11-cos7-armv7l >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libXxf86vm-1.1.4/COPYING
  summary: "(CDT) X.Org X11 libXxf86vm runtime library"
  description: |
        X.Org X11 libXxf86vm runtime library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
