package:
  name: libxi-devel-cos7-armv7l
  version: 1.7.9

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/libXi-devel-1.7.9-1.el7.armv7hl.rpm
    sha256: d0f2515fa6079dbbe3987dbf08200750e27673f2c2b302329a8fb5e70a8ade2c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/libXi-1.7.9-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxi-cos7-armv7l ==1.7.9 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxi-cos7-armv7l ==1.7.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*
  run:
    - libxi-cos7-armv7l ==1.7.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libxi-license
  summary: (CDT) X.Org X11 libXi development package
  description: |
    X.Org X11 libXi development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
