package:
  name: libxft-devel-cos6-x86_64
  version: 2.3.2

source:
  - url: https://vault.centos.org/6.10/os/x86_64/Packages/libXft-devel-2.3.2-1.el6.x86_64.rpm
    sha256: 3059b776f66acda0e2f9c0558f7d3be184b882a81243e748a85632c635bf243c
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libXft-2.3.2-1.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxft-cos6-x86_64 ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxft-cos6-x86_64 ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*
  run:
    - libxft-cos6-x86_64 ==2.3.2 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  license_file: libXft-license
  summary: (CDT) X.Org X11 libXft development package
  description: |
    X.Org X11 libXft development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
