package:
  name: fribidi-cos7-armv7l
  version: 1.0.2

source:
  - url: http://vault.centos.org/altarch/7/os/armhfp/Packages/fribidi-1.0.2-1.el7_7.1.armv7hl.rpm
    sha256: 79f4267d4549aa0f891ec6bace9424ab149389abb908d8c1cbf63eebbb23a59a
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/fribidi-1.0.2-1.el7_7.1.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-armv7l 2.17.*
  run:
    - sysroot_linux-armv7l 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/fribidi/fribidi/
  license: LGPLv2+ and UCD
  license_family: LGPL
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/fribidi-1.0.2/COPYING
  summary: "(CDT) Library implementing the Unicode Bidirectional Algorithm"
  description: |
        A library to handle bidirectional scripts (for example Hebrew, Arabic), so
        that the display is done in the proper way; while the text data itself is
        always written in logical order.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
